# Generated by Django 4.2.8 on 2026-04-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['segment_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('units_sold', models.IntegerField(default=0)),
                ('inventory_level', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('product_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
