# Generated by Django 4.2.8 on 2026-03-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, max_length=100, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='profile',
            name='governorate',
            field=models.CharField(blank=True, max_length=100, verbose_name='Governorate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Address'),
        ),
    ]
